### ISSUE TITLE
Errors with Imp Song and Sour Mouth

### ISSUE THREAD

**Issue by wrjones104** [AtmaTek/WorldsCollide#2]
I'm getting errors when generating seeds both locally and on the website when either the Sour Mouth or Imp Song results are selected. Traceback for an Imp Song error below:
```
Traceback (most recent call last):
  File "C:\Users\Will\PycharmProjects\worldscollide\wc.py", line 30, in <module>
    main()
  File "C:\Users\Will\PycharmProjects\worldscollide\wc.py", line 12, in main
    events = Events(memory.rom, args, data)
  File "C:\Users\Will\PycharmProjects\worldscollide\event\events.py", line 18, in __init__
    self.mod()
  File "C:\Users\Will\PycharmProjects\worldscollide\event\events.py", line 51, in mod
    event.mod()
  File "C:\Users\Will\PycharmProjects\worldscollide\event\ancient_castle.py", line 31, in mod
    self.finish_check_mod()
  File "C:\Users\Will\PycharmProjects\worldscollide\event\ancient_castle.py", line 110, in finish_check_mod
    field.FinishCheck(),
  File "C:\Users\Will\PycharmProjects\worldscollide\instruction\field\functions.py", line 137, in __init__
    CheckObjectives(),
  File "C:\Users\Will\PycharmProjects\worldscollide\instruction\field\functions.py", line 123, in __init__
    objective.check_complete.field(),
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\_check_complete.py", line 70, in field
    return Field(self.objective)
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\_check_complete.py", line 14, in __init__
    field.Call.__init__(self, self.address(*args, **kwargs))
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\_cached_function.py", line 14, in address
    self.space = self.write(*args, **kwargs)
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\_check_complete.py", line 23, in write
    objective.result.field(),
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\results\_objective_result.py", line 26, in field
    return self.field_class(*(self.args + args), **kwargs)
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\results\_field_result.py", line 8, in __init__
    field.Call.__init__(self, self.address(*args, **kwargs))
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\_cached_function.py", line 14, in address
    self.space = self.write(*args, **kwargs)
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\results\_field_result.py", line 12, in write
    self.src(*args, **kwargs),
  File "C:\Users\Will\PycharmProjects\worldscollide\objectives\results\imp_song.py", line 8, in src
    field.AddStatusEffects(Characters.PARTY0, field.Status.IMP),
AttributeError: type object 'Characters' has no attribute 'PARTY0'
```

**Comment by AtmaTek** [comment]
Fixed 6bc10684fa4f26ca4caf69434830c2795dbf605e
